[paths]
environments_path = "./environments"
extensions_dirs = ["extensions"]

[build]
skip_base_generation = true
extensions = ["oidc", "smtp", "step-ca-trust"]

[build.combos]
entire = ["oidc", "smtp"]
entire-trust = ["oidc", "smtp", "step-ca-trust"]

[build.environments]
available = ["forwarding", "letsencrypt", "step-ca"]

[build.environments.forwarding]
extensions = []
combos = ["entire"]

[build.environments.letsencrypt]
extensions = []
combos = ["entire"]

[build.environments.step-ca]
extensions = []
combos = ["entire-trust"]