[paths]
environments_path = "./environments"
extensions_dirs = ["extensions"]

[build]
extensions = ["oidc", "step-ca-trust"]

[build.combos]
oidc-trust = ["oidc", "step-ca-trust"]

[build.environments]
available = ["forwarding", "letsencrypt", "step-ca"]

[build.environments.forwarding]
extensions = ["oidc"]
combos = []

[build.environments.letsencrypt]
extensions = ["oidc"]
combos = []

[build.environments.step-ca]
extensions = []
combos = ["oidc-trust"]