x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "${LOG_MAX_SIZE:-10m}"
    max-file: "${LOG_MAX_FILE:-3}"
    compress: "${LOG_COMPRESS:-true}"

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    logging: *default-logging
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED:-true}
      INVITATIONS_ALLOWED: ${INVITATIONS_ALLOWED:-true}
    volumes:
      - vaultwarden-data:/data

volumes:
  vaultwarden-data:
    name: vaultwarden-data